; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy @ 5.1.0
board = teensy41
framework = arduino

build_flags =

    ; Override Teensy AudioStream.h defines
    -D AUDIO_BLOCK_SAMPLES=960
    -D AUDIO_SAMPLE_RATE_EXACT=48000
    ;-D USB_SERIAL

    ; If using USB audio, it must support 48KHz sample rates
    ; https://github.com/K7MDL2/KEITHSDR/wiki/48KHz-USB-Audio
    -D USB_AUDIO_48KHZ
    -D USB_AUDIO

    ; Opus Build Flags
    -D CONFIG_OPUS_BITRATE_MAX=128000
    -D CONFIG_OPUS_MODE
    -D OPUS_BUILD
    -D FIXED_POINT
    -D DISABLE_FLOAT_API
    -D OVERRIDE_OPUS_ALLOC_SCRATCH
    -D OVERRIDE_OPUS_ALLOC
    -D OVERRIDE_OPUS_FREE
    -D'opus_alloc(x)=NULL'
    -D'opus_free(x)=NULL'
    -D VAR_ARRAYS
    -D OPUS_ARM_INLINE_EDSP
    -D EMBEDDED_ARM
    -D OPUS_ARM_ASM
    -D CONFIG_OPUS_MODE_CELT=1
    -D CONFIG_OPUS_MODE_SILK=2

